version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - emqx

  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    environment:
      EMQX_NAME: emqx
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_LOG__LEVEL: debug
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  emqx_data:
  emqx_log: